package CompiladorAuto;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class MeuParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Sym.class;
}

  /** Default constructor. */
  @Deprecated
  public MeuParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public MeuParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public MeuParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\101\000\002\002\012\000\002\002\004\000\002\003" +
    "\004\000\002\003\002\000\002\004\005\000\002\004\002" +
    "\000\002\005\004\000\002\016\003\000\002\016\003\000" +
    "\002\016\003\000\002\006\004\000\002\006\002\000\002" +
    "\007\003\000\002\007\003\000\002\007\003\000\002\007" +
    "\003\000\002\007\003\000\002\007\003\000\002\007\003" +
    "\000\002\010\010\000\002\010\011\000\002\010\012\000" +
    "\002\011\004\000\002\011\004\000\002\011\002\000\002" +
    "\012\011\000\002\012\005\000\002\012\002\000\002\037" +
    "\002\000\002\040\002\000\002\013\007\000\002\014\005" +
    "\000\002\015\003\000\002\025\006\000\002\026\004\000" +
    "\002\026\002\000\002\036\006\000\002\017\003\000\002" +
    "\017\003\000\002\020\003\000\002\020\003\000\002\020" +
    "\003\000\002\020\003\000\002\020\003\000\002\021\007" +
    "\000\002\022\005\000\002\022\003\000\002\022\003\000" +
    "\002\023\004\000\002\023\002\000\002\024\003\000\002" +
    "\024\003\000\002\024\003\000\002\027\014\000\002\030" +
    "\003\000\002\030\003\000\002\030\002\000\002\032\005" +
    "\000\002\033\005\000\002\031\004\000\002\031\004\000" +
    "\002\031\002\000\002\034\007\000\002\035\005\000\002" +
    "\035\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\210\000\004\022\005\001\002\000\004\002\212\001" +
    "\002\000\004\023\006\001\002\000\004\044\007\001\002" +
    "\000\012\017\015\020\011\021\014\045\ufffe\001\002\000" +
    "\004\023\211\001\002\000\004\023\ufff9\001\002\000\004" +
    "\045\022\001\002\000\006\045\ufffc\046\016\001\002\000" +
    "\004\023\ufff8\001\002\000\004\023\ufffa\001\002\000\010" +
    "\017\015\020\011\021\014\001\002\000\004\045\uffff\001" +
    "\002\000\006\045\ufffc\046\016\001\002\000\004\045\ufffd" +
    "\001\002\000\004\040\023\001\002\000\030\004\031\005" +
    "\030\010\027\012\043\013\037\014\040\017\015\020\011" +
    "\021\014\023\034\041\ufff6\001\002\000\032\004\ufff4\005" +
    "\ufff4\010\ufff4\011\ufff4\012\ufff4\013\ufff4\014\ufff4\017\ufff4" +
    "\020\ufff4\021\ufff4\023\ufff4\041\ufff4\001\002\000\032\004" +
    "\ufff1\005\ufff1\010\ufff1\011\ufff1\012\ufff1\013\ufff1\014\ufff1" +
    "\017\ufff1\020\ufff1\021\ufff1\023\ufff1\041\ufff1\001\002\000" +
    "\004\041\210\001\002\000\004\044\204\001\002\000\004" +
    "\044\164\001\002\000\004\044\154\001\002\000\004\023" +
    "\151\001\002\000\032\004\ufff2\005\ufff2\010\ufff2\011\ufff2" +
    "\012\ufff2\013\ufff2\014\ufff2\017\ufff2\020\ufff2\021\ufff2\023" +
    "\ufff2\041\ufff2\001\002\000\010\024\143\031\142\032\144" +
    "\001\002\000\032\004\031\005\030\010\027\011\ufff6\012" +
    "\043\013\037\014\040\017\015\020\011\021\014\023\034" +
    "\041\ufff6\001\002\000\032\004\ufff5\005\ufff5\010\ufff5\011" +
    "\ufff5\012\ufff5\013\ufff5\014\ufff5\017\ufff5\020\ufff5\021\ufff5" +
    "\023\ufff5\041\ufff5\001\002\000\004\044\132\001\002\000" +
    "\004\044\114\001\002\000\032\004\ufff3\005\ufff3\010\ufff3" +
    "\011\ufff3\012\ufff3\013\ufff3\014\ufff3\017\ufff3\020\ufff3\021" +
    "\ufff3\023\ufff3\041\ufff3\001\002\000\032\004\ufff0\005\ufff0" +
    "\010\ufff0\011\ufff0\012\ufff0\013\ufff0\014\ufff0\017\ufff0\020" +
    "\ufff0\021\ufff0\023\ufff0\041\ufff0\001\002\000\004\044\045" +
    "\001\002\000\032\004\uffef\005\uffef\010\uffef\011\uffef\012" +
    "\uffef\013\uffef\014\uffef\017\uffef\020\uffef\021\uffef\023\uffef" +
    "\041\uffef\001\002\000\004\017\046\001\002\000\014\017" +
    "\015\020\011\021\014\023\047\047\uffc9\001\002\000\004" +
    "\024\112\001\002\000\004\023\106\001\002\000\004\047" +
    "\uffca\001\002\000\004\047\054\001\002\000\004\047\uffcb" +
    "\001\002\000\004\023\055\001\002\000\020\033\uffe1\034" +
    "\uffe1\035\uffe1\036\uffe1\037\uffe1\045\uffe1\047\uffe1\001\002" +
    "\000\014\033\102\034\100\035\077\036\104\037\101\001" +
    "\002\000\004\047\060\001\002\000\012\023\061\031\062" +
    "\032\065\045\uffc4\001\002\000\006\031\062\032\065\001" +
    "\002\000\006\023\uffdb\045\uffdb\001\002\000\004\023\075" +
    "\001\002\000\004\045\066\001\002\000\006\023\uffdc\045" +
    "\uffdc\001\002\000\004\040\070\001\002\000\032\004\uffcc" +
    "\005\uffcc\010\uffcc\011\uffcc\012\uffcc\013\uffcc\014\uffcc\017" +
    "\uffcc\020\uffcc\021\uffcc\023\uffcc\041\uffcc\001\002\000\030" +
    "\004\uffe5\005\uffe5\010\uffe5\012\uffe5\013\uffe5\014\uffe5\017" +
    "\uffe5\020\uffe5\021\uffe5\023\uffe5\041\uffe5\001\002\000\030" +
    "\004\031\005\030\010\027\012\043\013\037\014\040\017" +
    "\015\020\011\021\014\023\034\041\ufff6\001\002\000\004" +
    "\041\uffe4\001\002\000\004\041\074\001\002\000\034\004" +
    "\uffe3\005\uffe3\010\uffe3\011\uffe3\012\uffe3\013\uffe3\014\uffe3" +
    "\015\uffe3\017\uffe3\020\uffe3\021\uffe3\023\uffe3\041\uffe3\001" +
    "\002\000\004\045\uffc5\001\002\000\004\045\uffc6\001\002" +
    "\000\004\023\uffd8\001\002\000\004\023\uffd9\001\002\000" +
    "\004\023\uffd6\001\002\000\004\023\uffda\001\002\000\004" +
    "\023\055\001\002\000\004\023\uffd7\001\002\000\006\045" +
    "\uffe2\047\uffe2\001\002\000\006\024\107\047\uffde\001\002" +
    "\000\004\023\055\001\002\000\004\047\uffc8\001\002\000" +
    "\004\047\uffdf\001\002\000\004\023\055\001\002\000\004" +
    "\047\uffc7\001\002\000\010\023\115\051\120\052\117\001" +
    "\002\000\004\045\uffd2\001\002\000\004\045\130\001\002" +
    "\000\004\045\uffd3\001\002\000\012\023\121\051\uffd0\052" +
    "\122\053\124\001\002\000\012\023\uffcf\051\uffcf\052\uffcf" +
    "\053\uffcf\001\002\000\012\023\uffce\051\uffce\052\uffce\053" +
    "\uffce\001\002\000\004\051\127\001\002\000\012\023\uffcd" +
    "\051\uffcd\052\uffcd\053\uffcd\001\002\000\012\023\121\051" +
    "\uffd0\052\122\053\124\001\002\000\004\051\uffd1\001\002" +
    "\000\004\045\uffd4\001\002\000\004\047\131\001\002\000" +
    "\032\004\uffd5\005\uffd5\010\uffd5\011\uffd5\012\uffd5\013\uffd5" +
    "\014\uffd5\017\uffd5\020\uffd5\021\uffd5\023\uffd5\041\uffd5\001" +
    "\002\000\010\017\015\020\011\021\014\001\002\000\004" +
    "\023\134\001\002\000\004\050\135\001\002\000\004\023" +
    "\136\001\002\000\004\045\137\001\002\000\004\040\070" +
    "\001\002\000\032\004\uffec\005\uffec\010\uffec\011\uffec\012" +
    "\uffec\013\uffec\014\uffec\017\uffec\020\uffec\021\uffec\023\uffec" +
    "\041\uffec\001\002\000\006\011\ufff7\041\ufff7\001\002\000" +
    "\004\047\150\001\002\000\004\023\055\001\002\000\004" +
    "\047\145\001\002\000\032\004\uffc2\005\uffc2\010\uffc2\011" +
    "\uffc2\012\uffc2\013\uffc2\014\uffc2\017\uffc2\020\uffc2\021\uffc2" +
    "\023\uffc2\041\uffc2\001\002\000\004\047\147\001\002\000" +
    "\032\004\uffdd\005\uffdd\010\uffdd\011\uffdd\012\uffdd\013\uffdd" +
    "\014\uffdd\017\uffdd\020\uffdd\021\uffdd\023\uffdd\041\uffdd\001" +
    "\002\000\032\004\uffc1\005\uffc1\010\uffc1\011\uffc1\012\uffc1" +
    "\013\uffc1\014\uffc1\017\uffc1\020\uffc1\021\uffc1\023\uffc1\041" +
    "\uffc1\001\002\000\006\024\107\047\uffde\001\002\000\004" +
    "\047\153\001\002\000\032\004\uffe0\005\uffe0\010\uffe0\011" +
    "\uffe0\012\uffe0\013\uffe0\014\uffe0\017\uffe0\020\uffe0\021\uffe0" +
    "\023\uffe0\041\uffe0\001\002\000\004\023\055\001\002\000" +
    "\004\045\156\001\002\000\004\040\070\001\002\000\034" +
    "\004\uffe9\005\uffe9\010\uffe9\011\uffe9\012\uffe9\013\uffe9\014" +
    "\uffe9\015\160\017\uffe9\020\uffe9\021\uffe9\023\uffe9\041\uffe9" +
    "\001\002\000\012\004\031\005\030\013\037\040\070\001" +
    "\002\000\032\004\uffee\005\uffee\010\uffee\011\uffee\012\uffee" +
    "\013\uffee\014\uffee\017\uffee\020\uffee\021\uffee\023\uffee\041" +
    "\uffee\001\002\000\032\004\uffeb\005\uffeb\010\uffeb\011\uffeb" +
    "\012\uffeb\013\uffeb\014\uffeb\017\uffeb\020\uffeb\021\uffeb\023" +
    "\uffeb\041\uffeb\001\002\000\032\004\uffea\005\uffea\010\uffea" +
    "\011\uffea\012\uffea\013\uffea\014\uffea\017\uffea\020\uffea\021" +
    "\uffea\023\uffea\041\uffea\001\002\000\004\023\165\001\002" +
    "\000\004\045\166\001\002\000\004\040\167\001\002\000" +
    "\010\006\172\007\170\041\uffe6\001\002\000\004\050\202" +
    "\001\002\000\004\041\201\001\002\000\004\052\173\001" +
    "\002\000\004\050\174\001\002\000\030\004\031\005\030" +
    "\010\027\011\ufff6\012\043\013\037\014\040\017\015\020" +
    "\011\021\014\023\034\001\002\000\004\011\176\001\002" +
    "\000\004\047\177\001\002\000\010\006\172\007\170\041" +
    "\uffe6\001\002\000\004\041\uffe8\001\002\000\032\004\uffed" +
    "\005\uffed\010\uffed\011\uffed\012\uffed\013\uffed\014\uffed\017" +
    "\uffed\020\uffed\021\uffed\023\uffed\041\uffed\001\002\000\030" +
    "\004\031\005\030\010\027\012\043\013\037\014\040\017" +
    "\015\020\011\021\014\023\034\041\ufff6\001\002\000\004" +
    "\041\uffe7\001\002\000\004\023\055\001\002\000\004\045" +
    "\206\001\002\000\004\040\070\001\002\000\032\004\uffc3" +
    "\005\uffc3\010\uffc3\011\uffc3\012\uffc3\013\uffc3\014\uffc3\017" +
    "\uffc3\020\uffc3\021\uffc3\023\uffc3\041\uffc3\001\002\000\004" +
    "\002\001\001\002\000\006\045\ufffb\046\ufffb\001\002\000" +
    "\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\210\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\003\011\005\012" +
    "\016\007\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\004\016\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\005\017\016\007\001\001\000" +
    "\002\001\001\000\004\004\020\001\001\000\002\001\001" +
    "\000\002\001\001\000\026\006\025\007\034\010\035\016" +
    "\031\021\032\025\023\027\024\034\041\035\043\036\040" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\026\006\140\007\034\010\035\016\031\021\032\025\023" +
    "\027\024\034\041\035\043\036\040\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\016\047\030\051\032\052\033\050" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\014\056" +
    "\015\055\001\001\000\002\001\001\000\004\020\102\001" +
    "\001\000\002\001\001\000\006\017\062\031\063\001\001" +
    "\000\004\017\075\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\013\066" +
    "\001\001\000\002\001\001\000\004\037\070\001\001\000" +
    "\026\006\071\007\034\010\035\016\031\021\032\025\023" +
    "\027\024\034\041\035\043\036\040\001\001\000\004\040" +
    "\072\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\015\104" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\026" +
    "\107\001\001\000\004\015\110\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\015\112\001\001\000\002\001" +
    "\001\000\004\022\115\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\023\122\024\124\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\023\125\024\124\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\016\132\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\013\137\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\015\145\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\026\151\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\014\154\015\055\001\001\000" +
    "\002\001\001\000\004\013\156\001\001\000\004\011\160" +
    "\001\001\000\006\010\162\013\161\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\012\170\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\026\006\174\007\034\010\035\016" +
    "\031\021\032\025\023\027\024\034\041\035\043\036\040" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\012" +
    "\177\001\001\000\002\001\001\000\002\001\001\000\026" +
    "\006\202\007\034\010\035\016\031\021\032\025\023\027" +
    "\024\034\041\035\043\036\040\001\001\000\002\001\001" +
    "\000\006\014\204\015\055\001\001\000\002\001\001\000" +
    "\004\013\206\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$MeuParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$MeuParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$MeuParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$MeuParser$actions {
  private final MeuParser parser;

  /** Constructor */
  CUP$MeuParser$actions(MeuParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$MeuParser$do_action_part00000000(
    int                        CUP$MeuParser$act_num,
    java_cup.runtime.lr_parser CUP$MeuParser$parser,
    java.util.Stack            CUP$MeuParser$stack,
    int                        CUP$MeuParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$MeuParser$result;

      /* select the action based on the action number */
      switch (CUP$MeuParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // Prog ::= PROGRAMA ID AP ListaVarParametros FP ACHAVES ListaComandos FCHAVES 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("Prog",0, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-7)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= Prog EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-1)).value;
		RESULT = start_val;
              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-1)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$MeuParser$parser.done_parsing();
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // ListaVarParametros ::= Parametro MaisParametros 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("ListaVarParametros",1, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-1)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // ListaVarParametros ::= 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("ListaVarParametros",1, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // MaisParametros ::= V Parametro MaisParametros 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("MaisParametros",2, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-2)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // MaisParametros ::= 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("MaisParametros",2, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Parametro ::= Tipo ID 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("Parametro",3, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-1)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Tipo ::= INT 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("Tipo",12, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Tipo ::= STRING 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("Tipo",12, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Tipo ::= CHAR 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("Tipo",12, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // ListaComandos ::= Comando ListaComandos 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("ListaComandos",4, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-1)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // ListaComandos ::= 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("ListaComandos",4, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // Comando ::= EstruturaControle 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("Comando",5, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // Comando ::= DeclaracaoVariavel 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("Comando",5, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Comando ::= Atribuicao 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("Comando",5, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Comando ::= Print 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("Comando",5, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // Comando ::= For 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("Comando",5, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // Comando ::= While 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("Comando",5, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // Comando ::= Incremento 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("Comando",5, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // EstruturaControle ::= IF AP Condicao FP Bloco IfElse 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("EstruturaControle",6, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-5)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // EstruturaControle ::= SWITCH AP ID FP ACHAVES ListaCases FCHAVES 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-4)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-4)).value;
		
                        if (!TabelaSimbolos.existe((String) id.toString())) {
                            throw new Error("Variável não declarada: " + (String) id.toString());
                        }
                    
              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("EstruturaControle",6, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-6)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // EstruturaControle ::= FOREACH AP Tipo ID PP ID FP Bloco 
            {
              Object RESULT =null;
		int id1left = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-4)).left;
		int id1right = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-4)).right;
		Object id1 = (Object)((java_cup.runtime.Symbol) CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-4)).value;
		int id2left = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-2)).left;
		int id2right = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-2)).right;
		Object id2 = (Object)((java_cup.runtime.Symbol) CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-2)).value;
		
        String identificador1 = (String)((Symbol)id1).value;
        String identificador2 = (String)((Symbol)id2).value;
        if (!TabelaSimbolos.existe(identificador1) || !TabelaSimbolos.existe(identificador2)) {
            throw new Error("Variável não declarada");
        }
    
              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("EstruturaControle",6, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-7)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // IfElse ::= ELSE Bloco 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("IfElse",7, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-1)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // IfElse ::= ELSE EstruturaControle 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("IfElse",7, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-1)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // IfElse ::= 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("IfElse",7, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // ListaCases ::= CASE CONST PP ListaComandos BREAK PV ListaCases 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("ListaCases",8, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-6)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // ListaCases ::= DEFAULT PP ListaComandos 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("ListaCases",8, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-2)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // ListaCases ::= 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("ListaCases",8, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // NT$0 ::= 
            {
              Object RESULT =null;
 TabelaSimbolos.entrarEscopo("novo_escopo"); 
              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("NT$0",29, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // NT$1 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-1)).value;
 TabelaSimbolos.sairEscopo(); 
              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("NT$1",30, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // Bloco ::= ACHAVES NT$0 ListaComandos NT$1 FCHAVES 
            {
              Object RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-1)).value;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("Bloco",9, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-4)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // Condicao ::= Expressao Comparador Expressao 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$MeuParser$stack.peek()).value;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("Condicao",10, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-2)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // Expressao ::= ID 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$MeuParser$stack.peek()).value;
		
        String identificador = (String)((Symbol)id).value;
        if (!TabelaSimbolos.existe(identificador)) {
            throw new Error("Variável não declarada: " + identificador);
        }
    
              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("Expressao",11, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // DeclaracaoVariavel ::= Tipo ID InicializacaoVariavel PV 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-3)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-3)).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-3)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-2)).value;
		int ivleft = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-1)).left;
		int ivright = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-1)).right;
		Object iv = (Object)((java_cup.runtime.Symbol) CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-1)).value;
		
        String tipoVar = (String)((Symbol)t).value;
        String nomeVar = (String)((Symbol)id).value;
        InfoVariavel infoVar = new InfoVariavel(tipoVar, "local");
        TabelaSimbolos.adicionar(nomeVar, infoVar);
    
              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("DeclaracaoVariavel",19, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-3)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // InicializacaoVariavel ::= IGUAL Expressao 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("InicializacaoVariavel",20, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-1)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // InicializacaoVariavel ::= 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("InicializacaoVariavel",20, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // Atribuicao ::= ID IGUAL Expressao PV 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-3)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-1)).value;
		
        if (!TabelaSimbolos.existe((String) id.toString())) {
            throw new Error("Variável não declarada: " + (String) id.toString());
        }
        // Adicione lógica para verificar compatibilidade de tipos aqui.
    
              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("Atribuicao",28, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-3)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // Operacao ::= MAISMAIS 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("Operacao",13, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // Operacao ::= MENOSMENOS 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("Operacao",13, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // Comparador ::= MAIORQ 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("Comparador",14, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // Comparador ::= MENORQ 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("Comparador",14, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // Comparador ::= MENORIGUAL 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("Comparador",14, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // Comparador ::= MAIORIQUAL 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("Comparador",14, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // Comparador ::= IGUALIGUAL 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("Comparador",14, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // Print ::= PRINT AP PrintConteudo FP PV 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("Print",15, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-4)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // PrintConteudo ::= ASPAS StringChars ASPAS 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("PrintConteudo",16, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-2)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // PrintConteudo ::= CONST 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("PrintConteudo",16, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // PrintConteudo ::= ID 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$MeuParser$stack.peek()).value;
		
                    String identificador = (String)((Symbol)id).value;
                    if (!TabelaSimbolos.existe(identificador)) {
                        throw new Error("Variável não declarada: " + identificador);
                    }
                
              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("PrintConteudo",16, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // StringChars ::= StringChar StringChars 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("StringChars",17, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-1)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // StringChars ::= 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("StringChars",17, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // StringChar ::= ID 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$MeuParser$stack.peek()).value;
		
                 if (!TabelaSimbolos.existe((String) id.toString())) {
                     throw new Error("Variável não declarada: " + (String) id.toString());
                 }
             
              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("StringChar",18, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // StringChar ::= CONST 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("StringChar",18, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // StringChar ::= ESPACO 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("StringChar",18, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // For ::= FOR AP INT ForInicializacao PV Condicao PV ForIteracao FP Bloco 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("For",21, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-9)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // ForInicializacao ::= DeclaracaoVariavelFor 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("ForInicializacao",22, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // ForInicializacao ::= AtribuicaoFor 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("ForInicializacao",22, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // ForInicializacao ::= 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("ForInicializacao",22, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // DeclaracaoVariavelFor ::= Tipo ID InicializacaoVariavel 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("DeclaracaoVariavelFor",24, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-2)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // AtribuicaoFor ::= ID IGUAL Expressao 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-2)).value;
		
                    if (!TabelaSimbolos.existe((String) id.toString())) {
                        throw new Error("Variável não declarada: " + (String) id.toString());
                    }
                
              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("AtribuicaoFor",25, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-2)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // ForIteracao ::= ID Operacao 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-1)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-1)).value;
		
                  if (!TabelaSimbolos.existe((String) id.toString())) {
                      throw new Error("Variável não declarada: " + (String) id.toString());
                  }
              
              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("ForIteracao",23, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-1)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // ForIteracao ::= Operacao ID 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$MeuParser$stack.peek()).value;
		
                  if (!TabelaSimbolos.existe((String) id.toString())) {
                      throw new Error("Variável não declarada: " + (String) id.toString());
                  }
              
              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("ForIteracao",23, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-1)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // ForIteracao ::= 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("ForIteracao",23, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // While ::= WHILE AP Condicao FP Bloco 
            {
              Object RESULT =null;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("While",26, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-4)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // Incremento ::= ID MAISMAIS PV 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-2)).value;

              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("Incremento",27, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-2)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // Incremento ::= ID MENOSMENOS PV 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-2)).value;
		
                 if (!TabelaSimbolos.existe((String) id.toString())) {
                     throw new Error("Variável não declarada: " + (String) id.toString());
                 }
             
              CUP$MeuParser$result = parser.getSymbolFactory().newSymbol("Incremento",27, ((java_cup.runtime.Symbol)CUP$MeuParser$stack.elementAt(CUP$MeuParser$top-2)), ((java_cup.runtime.Symbol)CUP$MeuParser$stack.peek()), RESULT);
            }
          return CUP$MeuParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$MeuParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$MeuParser$do_action(
    int                        CUP$MeuParser$act_num,
    java_cup.runtime.lr_parser CUP$MeuParser$parser,
    java.util.Stack            CUP$MeuParser$stack,
    int                        CUP$MeuParser$top)
    throws java.lang.Exception
    {
              return CUP$MeuParser$do_action_part00000000(
                               CUP$MeuParser$act_num,
                               CUP$MeuParser$parser,
                               CUP$MeuParser$stack,
                               CUP$MeuParser$top);
    }
}

}
