package CompiladorAuto;


//----------------------------------------------------
//The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
/* terminals */
public static final int PP = 38;
public static final int MENOSMENOS = 23;
public static final int MULT = 21;
public static final int CONST = 40;
public static final int V = 36;
public static final int CHAR = 15;
public static final int SOMA = 19;
public static final int PROGRAMA = 16;
public static final int MENORQ = 26;
public static final int CASE = 4;
public static final int MAIORQ = 25;
public static final int INT = 13;
public static final int FOR = 8;
public static final int MENORIGUAL = 27;
public static final int FP = 35;
public static final int IGUAL = 18;
public static final int MAIORIQUAL = 28;
public static final int ACOL = 32;
public static final int ACHAVES = 30;
public static final int FCHAVES = 31;
public static final int FCOL = 33;
public static final int DIV = 20;
public static final int IF = 2;
public static final int ID = 17;
public static final int ESPACO = 41;
public static final int EOF = 0;
public static final int MAISMAIS = 24;
public static final int error = 1;
public static final int BREAK = 7;
public static final int SWITCH = 3;
public static final int FOREACH = 9;
public static final int ELSE = 11;
public static final int IGUALIGUAL = 29;
public static final int WHILE = 6;
public static final int DEFAULT = 5;
public static final int SUBT = 22;
public static final int STRING = 14;
public static final int ASPAS = 39;
public static final int AP = 34;
public static final int PRINT = 10;
public static final int DO = 12;
public static final int PV = 37;
public static final String[] terminalNames = new String[] {
"EOF",
"error",
"IF",
"SWITCH",
"CASE",
"DEFAULT",
"WHILE",
"BREAK",
"FOR",
"FOREACH",
"PRINT",
"ELSE",
"DO",
"INT",
"STRING",
"CHAR",
"PROGRAMA",
"ID",
"IGUAL",
"SOMA",
"DIV",
"MULT",
"SUBT",
"MENOSMENOS",
"MAISMAIS",
"MAIORQ",
"MENORQ",
"MENORIGUAL",
"MAIORIQUAL",
"IGUALIGUAL",
"ACHAVES",
"FCHAVES",
"ACOL",
"FCOL",
"AP",
"FP",
"V",
"PV",
"PP",
"ASPAS",
"CONST",
"ESPACO"
};
}

